config/routes.rb
Rails.application.routes.draw do
	root "cmanager#index"
	get 'cmanager/index'
	
	# ReactJS Callbacks somewhat API
	get '/getuserid', to: 'users#json_id_current_user'
	post '/newcampaign', to: 'campaigns#create_json'
	get '/showcampaign', to: 'campaigns#show_json'
	delete '/deletecampaign/:id', to: 'campaigns#destroy_json'
	post '/newbanner', to: 'banners#create_json'
	get '/showbanner', to: 'banners#show_json'
	delete '/deletebanner/:id', to: 'banners#destroy_json'
	# Public URL for banners
	get '/publicbanner(/*ip)', to: 'cmanager#get_public_banner', format: false

	resources :users do
		resources :campaigns
		resources :banners
	end
	#resources :campaigns
	
	# Authentication 
	get '/newuser', to: 'users#new'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCampaignManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" crossorigin="anonymous">
  </head>

  <body>
    <!-- Navigation bar for whole app -->
    <nav class="navbar">
      <div class="container-fluid">
        <ul class="nav navbar-left">
          <li class="mx-3"><%= link_to "Home", root_url %></li>  
        <% if sess_loggedin? %>
            <% @user ||= User.find_by(id: session[:user_id]) %>
            <li class="mx-3"><%= link_to "Campaigns", user_campaigns_path(@user) %></li> 
            <li class="mx-3"><%= link_to "Banners", user_banners_path(@user) %></li> 
            <li class="mx-3"><%= link_to "User Profile", user_path(@user) %></li> 
            <li class="mx-3"><%= link_to "Logout", logout_path, method: :delete %></li> 
        <% else %>
            <li class="mx-3"><%= link_to "New User Sign Up", newuser_path %></li>
            <li class="mx-3"><%= link_to "Login", login_path %></li>           
        <% end %>
        </ul>
      </div>
    </nav>

    <div class="body">
      <!-- Appearing messages for whole app for whole app -->
      <% flash.each do |flash_type, flash_msg| %>
        <div class="alert alert-<%= flash_type %>"><%= flash_msg %></div>
      <% end %>
      <%= yield %>
    </div>  
  </body>
</html>